/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coding4fun.kafka.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ShiftChanged extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8811079513109901331L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShiftChanged\",\"namespace\":\"com.coding4fun.kafka.models\",\"fields\":[{\"name\":\"CureEquipmentId\",\"type\":\"string\"},{\"name\":\"ShiftCode\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShiftChanged> ENCODER =
      new BinaryMessageEncoder<ShiftChanged>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShiftChanged> DECODER =
      new BinaryMessageDecoder<ShiftChanged>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ShiftChanged> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ShiftChanged> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ShiftChanged> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ShiftChanged>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ShiftChanged to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ShiftChanged from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ShiftChanged instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ShiftChanged fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence CureEquipmentId;
   private java.lang.CharSequence ShiftCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShiftChanged() {}

  /**
   * All-args constructor.
   * @param CureEquipmentId The new value for CureEquipmentId
   * @param ShiftCode The new value for ShiftCode
   */
  public ShiftChanged(java.lang.CharSequence CureEquipmentId, java.lang.CharSequence ShiftCode) {
    this.CureEquipmentId = CureEquipmentId;
    this.ShiftCode = ShiftCode;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CureEquipmentId;
    case 1: return ShiftCode;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CureEquipmentId = (java.lang.CharSequence)value$; break;
    case 1: ShiftCode = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'CureEquipmentId' field.
   * @return The value of the 'CureEquipmentId' field.
   */
  public java.lang.CharSequence getCureEquipmentId() {
    return CureEquipmentId;
  }


  /**
   * Sets the value of the 'CureEquipmentId' field.
   * @param value the value to set.
   */
  public void setCureEquipmentId(java.lang.CharSequence value) {
    this.CureEquipmentId = value;
  }

  /**
   * Gets the value of the 'ShiftCode' field.
   * @return The value of the 'ShiftCode' field.
   */
  public java.lang.CharSequence getShiftCode() {
    return ShiftCode;
  }


  /**
   * Sets the value of the 'ShiftCode' field.
   * @param value the value to set.
   */
  public void setShiftCode(java.lang.CharSequence value) {
    this.ShiftCode = value;
  }

  /**
   * Creates a new ShiftChanged RecordBuilder.
   * @return A new ShiftChanged RecordBuilder
   */
  public static com.coding4fun.kafka.models.ShiftChanged.Builder newBuilder() {
    return new com.coding4fun.kafka.models.ShiftChanged.Builder();
  }

  /**
   * Creates a new ShiftChanged RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShiftChanged RecordBuilder
   */
  public static com.coding4fun.kafka.models.ShiftChanged.Builder newBuilder(com.coding4fun.kafka.models.ShiftChanged.Builder other) {
    if (other == null) {
      return new com.coding4fun.kafka.models.ShiftChanged.Builder();
    } else {
      return new com.coding4fun.kafka.models.ShiftChanged.Builder(other);
    }
  }

  /**
   * Creates a new ShiftChanged RecordBuilder by copying an existing ShiftChanged instance.
   * @param other The existing instance to copy.
   * @return A new ShiftChanged RecordBuilder
   */
  public static com.coding4fun.kafka.models.ShiftChanged.Builder newBuilder(com.coding4fun.kafka.models.ShiftChanged other) {
    if (other == null) {
      return new com.coding4fun.kafka.models.ShiftChanged.Builder();
    } else {
      return new com.coding4fun.kafka.models.ShiftChanged.Builder(other);
    }
  }

  /**
   * RecordBuilder for ShiftChanged instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShiftChanged>
    implements org.apache.avro.data.RecordBuilder<ShiftChanged> {

    private java.lang.CharSequence CureEquipmentId;
    private java.lang.CharSequence ShiftCode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.coding4fun.kafka.models.ShiftChanged.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CureEquipmentId)) {
        this.CureEquipmentId = data().deepCopy(fields()[0].schema(), other.CureEquipmentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ShiftCode)) {
        this.ShiftCode = data().deepCopy(fields()[1].schema(), other.ShiftCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ShiftChanged instance
     * @param other The existing instance to copy.
     */
    private Builder(com.coding4fun.kafka.models.ShiftChanged other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.CureEquipmentId)) {
        this.CureEquipmentId = data().deepCopy(fields()[0].schema(), other.CureEquipmentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ShiftCode)) {
        this.ShiftCode = data().deepCopy(fields()[1].schema(), other.ShiftCode);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'CureEquipmentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCureEquipmentId() {
      return CureEquipmentId;
    }


    /**
      * Sets the value of the 'CureEquipmentId' field.
      * @param value The value of 'CureEquipmentId'.
      * @return This builder.
      */
    public com.coding4fun.kafka.models.ShiftChanged.Builder setCureEquipmentId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CureEquipmentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CureEquipmentId' field has been set.
      * @return True if the 'CureEquipmentId' field has been set, false otherwise.
      */
    public boolean hasCureEquipmentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CureEquipmentId' field.
      * @return This builder.
      */
    public com.coding4fun.kafka.models.ShiftChanged.Builder clearCureEquipmentId() {
      CureEquipmentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ShiftCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getShiftCode() {
      return ShiftCode;
    }


    /**
      * Sets the value of the 'ShiftCode' field.
      * @param value The value of 'ShiftCode'.
      * @return This builder.
      */
    public com.coding4fun.kafka.models.ShiftChanged.Builder setShiftCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ShiftCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ShiftCode' field has been set.
      * @return True if the 'ShiftCode' field has been set, false otherwise.
      */
    public boolean hasShiftCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ShiftCode' field.
      * @return This builder.
      */
    public com.coding4fun.kafka.models.ShiftChanged.Builder clearShiftCode() {
      ShiftCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShiftChanged build() {
      try {
        ShiftChanged record = new ShiftChanged();
        record.CureEquipmentId = fieldSetFlags()[0] ? this.CureEquipmentId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ShiftCode = fieldSetFlags()[1] ? this.ShiftCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShiftChanged>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShiftChanged>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShiftChanged>
    READER$ = (org.apache.avro.io.DatumReader<ShiftChanged>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.CureEquipmentId);

    out.writeString(this.ShiftCode);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.CureEquipmentId = in.readString(this.CureEquipmentId instanceof Utf8 ? (Utf8)this.CureEquipmentId : null);

      this.ShiftCode = in.readString(this.ShiftCode instanceof Utf8 ? (Utf8)this.ShiftCode : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.CureEquipmentId = in.readString(this.CureEquipmentId instanceof Utf8 ? (Utf8)this.CureEquipmentId : null);
          break;

        case 1:
          this.ShiftCode = in.readString(this.ShiftCode instanceof Utf8 ? (Utf8)this.ShiftCode : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










