// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.coding4fun.kafka.models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ShiftChanged : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ShiftChanged\",\"namespace\":\"com.coding4fun.kafka.models\"," +
				"\"fields\":[{\"name\":\"CureEquipmentId\",\"type\":\"string\"},{\"name\":\"ShiftCode\",\"type\":" +
				"\"string\"}]}");
		private string _CureEquipmentId;
		private string _ShiftCode;
		public virtual Schema Schema
		{
			get
			{
				return ShiftChanged._SCHEMA;
			}
		}
		public string CureEquipmentId
		{
			get
			{
				return this._CureEquipmentId;
			}
			set
			{
				this._CureEquipmentId = value;
			}
		}
		public string ShiftCode
		{
			get
			{
				return this._ShiftCode;
			}
			set
			{
				this._ShiftCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CureEquipmentId;
			case 1: return this.ShiftCode;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CureEquipmentId = (System.String)fieldValue; break;
			case 1: this.ShiftCode = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
